// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"atlas-doc/internal/biz"
	"atlas-doc/internal/conf"
	"atlas-doc/internal/data"
	"atlas-doc/internal/model"
	"atlas-doc/internal/server"
	"atlas-doc/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, file *conf.File, logger log.Logger) (*kratos.App, func(), error) {
	db := model.NewDB(confData)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	fileRepo := data.NewFileRepo(dataData, logger)
	fileUseCase := biz.NewFileUseCase(fileRepo, file, logger)
	fileService := service.NewFileService(fileUseCase)
	grpcServer := server.NewGRPCServer(confServer, fileService, logger)
	httpServer := server.NewHTTPServer(confServer, fileService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
